### ISSUE TITLE
NullPointerException on setOnClickListener

### ISSUE THREAD

**Issue by mouri11** [BytesClub/Tabcalc#1]
The onClickListener cannot find the current view and its elements, and is throwing the above exception. To stop the exception from crashin the app, comment out the line containing the loop with findViewById()(the line causing the mayhem) in the click listeners.

**Comment by mouri11** [comment]
Help received from Amit Tiwary
Solution: initialize buttons in the fragment, send the strings from fragment to main activity. Yet to implement.

**Comment by RudraNilBasu** [comment]
@mouri11 is this issue solved?

**Comment by mouri11** [comment]
Yes, this issue is solved. I am closing this issue.

**Comment by RudraNilBasu** [comment]
Is there any commit pushed in the repository that solves the issue?


             Rudra

**Comment by mouri11** [comment]
No. I haven't yet pushed the commit. There is a new issue I'm dealing with right now.
