### ISSUE TITLE
localProperties file should not be there

### ISSUE THREAD

**Issue by RudraNilBasu** [BytesClub/Tabcalc#3]
Most probably the file (https://github.com/BytesClub/Tabcalc/blob/master/local.properties) was added after adding it in the gitignore (https://github.com/BytesClub/Tabcalc/blob/master/.gitignore#L21)

It shouldn't be there, since it is generated by Android studio

**Comment by devutsav** [comment]
Check the PR

**Comment by RudraNilBasu** [comment]
Fixed in #4
