### ISSUE TITLE
"Press clear to continue" to be shown only once per session

### ISSUE THREAD

**Issue by RudraNilBasu** [BytesClub/Tabcalc#5]
Currently, the "Press clear to continue" message is shown every time the "=" button is pressed, it will be better to show it only once per session at least

**Comment by RudraNilBasu** [comment]
@devutsav do you want to work on it?

**Comment by devutsav** [comment]
yes @RudraNilBasu

**Comment by RudraNilBasu** [comment]
Assigned @devutsav 
This may seem interesting: https://bytesclub.github.io/contributing/#tips-for-contribution

**Comment by RudraNilBasu** [comment]
Fixed in #9
