### ISSUE TITLE
Make app have fixed layout

### ISSUE THREAD

**Issue by mouri11** [BytesClub/Tabcalc#6]
The app looks bad when it automatically rotates to adjust the orientation of the device. Need a way to stop it from rotating altogether.

**Comment by amitiwary999** [comment]
@mouri11 @devutsav you can use different layout for landscape and portrait mode. App can automatically detect rotation and use  respective layout.
[reference](https://stackoverflow.com/questions/2124046/how-do-i-specify-different-layouts-for-portrait-and-landscape-orientations).

**Comment by mouri11** [comment]
Fixed the rotating layout. Closing issue.
